ICON_BASEPATH = 'gui/html/img/logo/'
ICON_UNREAD = ICON_BASEPATH + 'smallunread.svg'
ICON_ACTIVE = ICON_BASEPATH + 'smallactive.svg'
ICON_INACTIVE = ICON_BASEPATH + 'smallbw.svg'
ICON_ERROR = ICON_BASEPATH + 'smallerror.svg'
